package UserLoginSystem;

import java.io.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.ArrayList;
import java.util.List;

public class SupplierDetails {

    private String SupplierCode;
    private String SupplierName;
    private String SupplierPhoneNumber;
    private String SupplierEmailAddress;
    private String SupplierAddress;
    private String ItemID;

    public SupplierDetails(String SupplierCode, String SupplierName, String SupplierPhoneNumber, String SupplierEmailAddress, String SupplierAddress, String ItemID) {
        this.SupplierCode = SupplierCode;
        this.SupplierName = SupplierName;
        this.SupplierPhoneNumber = SupplierPhoneNumber;
        this.SupplierEmailAddress = SupplierEmailAddress;
        this.SupplierAddress = SupplierAddress;
        this.ItemID = ItemID;
    }

    public String getSupplierCode() {
        return SupplierCode;
    }

    public String getSupplierName() {
        return SupplierName;
    }

    public String getSupplierPhoneNumber() {
        return SupplierPhoneNumber;
    }

    public String getSupplierEmailAddress() {
        return SupplierEmailAddress;
    }

    public String getSupplierAddress() {
        return SupplierAddress;
    }

    public String getItemID() {
        return ItemID;
    }

    // i didnt use this
    @Override
    public String toString() {
        return SupplierCode + ";" + SupplierName + ";" + SupplierPhoneNumber + ";" + SupplierEmailAddress + ";" + SupplierAddress + ";" + ItemID;
    }

    public static void addSupplierDetail() {
        List<SupplierDetails> supplierList = new ArrayList<>(); //Storing the parameterized constructor into the list named as SupplierList using ArrayList
        Scanner SupplierInputs = new Scanner(System.in);

        int SupplierNo;
        String autogeneratedSupplierCode = null;
        for (int i = 1; i <= 9999; i++) {
            SupplierNo = i;
            autogeneratedSupplierCode = String.format("S%04d", SupplierNo);
            boolean x = checkSupplierCode(autogeneratedSupplierCode);//if the Supplier code exist, it return false
            if (x) {
                break;
            } //if x is true, then it break the loop
        }

        System.out.println("Supplier Entry");
        System.out.println("Enter Supplier Name:");
        String SupplierName = SupplierInputs.nextLine();
        System.out.println("Enter Supplier Phone Number:");
        String SupplierPhoneNumber = SupplierInputs.nextLine();
        System.out.println("Enter Supplier Email Address:");
        String SupplierEmailAddress = SupplierInputs.nextLine();
        System.out.println("Enter Supplier Address:");
        String SupplierAddress = SupplierInputs.nextLine();
        System.out.println("Enter Item ID:");
        String ItemID = SupplierInputs.nextLine();

        SupplierDetails Supplier = new SupplierDetails(autogeneratedSupplierCode, SupplierName, SupplierPhoneNumber, SupplierEmailAddress, SupplierAddress, ItemID);
        supplierList.add(Supplier);

        boolean validInput = false;
        while (!validInput) {
            System.out.println("Would you like to save the record?[yes/no]");
            Scanner scanner = new Scanner(System.in);
            String input = scanner.nextLine().trim().toLowerCase();

            switch (input) {
                case "yes" -> {
                    try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("SupplierList.txt", true))) {
                        //bufferedWriter.write(System.lineSeparator());
                        //bufferedWriter.write("Supplier Code; Name; Phone Number; Email; Address; Item ID");

                        bufferedWriter.write(System.lineSeparator());
                        bufferedWriter.write(Supplier.toString());

                        try (BufferedWriter bufferedWriterRaw = new BufferedWriter(new FileWriter("SupplierListraw.txt", true))) {
                            bufferedWriterRaw.write(String.format("%-20s %-20s %-20s %-20s %-20s %-20s %n", "Supplier Code", "Name", "Phone Number", "Email", "Address", "Item ID"));
                            bufferedWriterRaw.write(String.format("%-20s %-20s %-20s %-20s %-20s %-20s %n", autogeneratedSupplierCode, SupplierName, SupplierPhoneNumber, SupplierEmailAddress, SupplierAddress, ItemID));
                        }
                    } catch (IOException e) {
                        System.out.println("Error while saving the record!");
                    }

                    System.out.println("The list is saved as SupplierList.txt");
                    validInput = true;
                }
                case "no" -> {
                    System.out.println("Are you sure to discard the record?");
                    validInput = true;
                }
                default ->
                    System.out.println("Invalid input.Please enter yes or no");

            }

        }
    }

    public static boolean checkSupplierCode(String suppliercode) {
        try {
            File SupplierList = new File("SupplierList.txt");
            if (SupplierList.exists()) {
                try (Scanner SupplierListFileScanner = new Scanner(SupplierList)) {
                    while (SupplierListFileScanner.hasNextLine()) {
                        String line = SupplierListFileScanner.nextLine();
                        if (!line.trim().isEmpty()) {
                            String[] supplierlist = line.split(";");

                            if (supplierlist[0].equals(suppliercode)) {
                                return false;
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            System.out.println("Error!");
        }
        return true;
    }

    public static void deleteSupplierDetail() {
        List<SupplierDetails> supplierList = new ArrayList<>();
        List<String> supplierlist = new ArrayList<>();
        Scanner deleteScanner = new Scanner(System.in);
        System.out.println("Enter the Supplier Code to delete:");
        String CodeForDelete = deleteScanner.nextLine();
        try {
            File SupplierList = new File("SupplierList.txt");
            BufferedReader reader = new BufferedReader(new FileReader(SupplierList));
            String line;
            int lineNumber = 0;
            int LineNumber = 0;
            String SetError = null;
//here is right
            while ((line = reader.readLine()) != null) {
                supplierlist.add(line);//the program read the output text file and directly put each line into the list
                lineNumber++;
                String[] supplier_list = line.split(";");

                if (supplier_list[0].equals(CodeForDelete)) {
                    LineNumber = lineNumber - 1; //minus 1 due to the index of list start from 0
                    SetError = CodeForDelete;

                }
            }

            if (SetError != null) {
                supplierlist.remove(LineNumber);
                boolean validInput = false;
                while (!validInput) {
                    System.out.println("Would you like to delete the record?[yes/no]");
                    Scanner scanner = new Scanner(System.in);
                    String input = scanner.nextLine().trim().toLowerCase();
                    switch (input) {
                        case "yes" -> {
                            try (BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("SupplierList1.txt"))) { //change the SupplierList1 to SupplierList
                                for (String printline : supplierlist) {
                                    bufferedWriter.write(printline + System.lineSeparator());
                                }
                            }
                            System.out.println("The list is saved as SupplierList.txt");
                            validInput = true;
                        }
                        case "no" -> {
                            System.out.println("Are you sure to cancel the deletion?");
                            validInput = true;
                        }
                        default ->
                            System.out.println("Invalid input.Please enter yes or no");
                    }
                }
            } else {
                System.out.println("Supplier Code  not exist!");
            }
            //until here

        } catch (IOException e) {
            System.out.println("Sorry, there is no Supplier Detail!");
        }
    }

    public static void editSupplierDetail() {
        //List<SupplierDetails> EditSupplierList = new ArrayList<>(); 
        List<String> editsupplierlist = new ArrayList<>();
        Scanner EditScanner = new Scanner(System.in);
        System.out.println("Enter the Supplier Code to edit the Supplier Detail:");
        String CodeForEdit = EditScanner.nextLine();

        try (BufferedReader reader = new BufferedReader(new FileReader("SupplierList1.txt"))) {
            //StringBuilder content = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                //content.append(line).append("\n");
                editsupplierlist.add(line);
            }
            //String newContent = content.toString().replace(SupplierDetails, NewSupplierDetails);
            System.out.println(editsupplierlist);

        } catch (IOException e) {
            System.out.println("Error!");
        }

        /*
        try{
            File EditSupplierListFile = new File("SupplierList.txt");
            BufferedReader reader = new BufferedReader(new FileReader(EditSupplierListFile));
            String line;
            int lineNumber = 0;
            int LineNumber = 0;
            while ((line = reader.readLine()) != null){
                editsupplierlist.add(line);
                lineNumber++;
                String[] Edit_SupplierList = line.split(";");
                if (Edit_SupplierList[0].equals(CodeForEdit)) {
                    LineNumber = lineNumber -1;
                
                }
            }
        }catch (IOException e){System.out.println("Error!");}
        
         */
    }

    public static void editSupplier() {

        Scanner EditScanner = new Scanner(System.in);
        Scanner NewInput = new Scanner(System.in);
        List<SupplierDetails> detailtoEdit = new ArrayList<>();
        List<String> editsupplierlist = new ArrayList<>();

        System.out.println("Enter the Supplier Code to edit the details");
        String codeForEdit = EditScanner.nextLine();
        try (BufferedReader reader = new BufferedReader(new FileReader("SupplierList.txt"))) {

            String line;
            while ((line = reader.readLine()) != null) {
                editsupplierlist.add(line);
                String[] editsupplier_list = line.split(";");
                detailtoEdit.add(new SupplierDetails(
                        editsupplier_list[0], 
                        editsupplier_list[1], 
                        editsupplier_list[2], 
                        editsupplier_list[3], 
                        editsupplier_list[4], 
                        editsupplier_list[5]));

                System.out.println(detailtoEdit);

                if (editsupplier_list[0].equals(codeForEdit)) {

                    SupplierDetails newDetails = null;

                    for (SupplierDetails detail : detailtoEdit) {
                        if (detail.getSupplierCode().equals(codeForEdit)) {
                            newDetails = detail;
                            break;
                        }
                    }

                    System.out.println("Enter Supplier Name:");
                    String NewSupplierName = NewInput.nextLine();
                    System.out.println("Enter Supplier Phone Number:");
                    String NewSupplierPhoneNumber = NewInput.nextLine();
                    System.out.println("Enter Supplier Email Address:");
                    String NewSupplierEmailAddress = NewInput.nextLine();
                    System.out.println("Enter Supplier Address:");
                    String NewSupplierAddress = NewInput.nextLine();
                    System.out.println("Enter Item ID:");
                    String NewItemID = NewInput.nextLine();

                    newDetails.SupplierName = NewSupplierName;
                    newDetails.SupplierPhoneNumber = NewSupplierPhoneNumber;
                    newDetails.SupplierEmailAddress = NewSupplierEmailAddress;
                    newDetails.SupplierAddress = NewSupplierAddress;
                    newDetails.ItemID = NewItemID;

                    System.out.println(newDetails.toString());

                }
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("SupplierList1.txt"))) {
                    for (SupplierDetails detail : detailtoEdit) {
                        writer.write(detail.toString());
                        writer.write(System.lineSeparator());
                    }

                }
            }
        } catch (IOException e) {
            System.out.println("Error!");
        }
    }
}
